export const GET_PROFILE = "GET_PROFILE";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const ITEMS_LOADING = "ITEMS_LOADING";
export const SINGLE_ITEM_LOADING = "SINGLE_ITEM_LOADING";
