// Product constants
export const GET_PROFILE = "GET_PROFILE";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const ITEMS_LOADING = "ITEMS_LOADING";
export const SINGLE_ITEM_LOADING = "SINGLE_ITEM_LOADING";

export const ADD_PRODUCT = "ADD_PRODUCT";
export const END_REQUEST = "END_REQUEST";
export const START_REQUEST = "START_REQUEST";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const EMAIL_NOTIFICATION_ON = "EMAIL_NOTIFICATION_ON";
export const EMAIL_NOTIFICATION_OFF = "EMAIL_NOTIFICATION_OFF";
